version: "3"
tasks:
  setup:
    desc: Setup development environment
    cmds:
      - cp .env.example .env
      - docker compose up -d

  test:
    desc: Run all tests
    cmds:
      - cd backend-go && go test ./...
      - cd shlyux && npm test

  lint:
    desc: Run linters
    cmds:
      - ./scripts/lint.sh
